- lib/screens/login_page.dart
- lib/screens/signup_page.dart
I have done following two changes to make app a little better 
1 - TextForField text is more readable #4 
2 - When the app is closed and the keyboard was open , on re-opening the app the keyboard is still there. Solved this is by adding a GestureDetector on Scaffold and adding onTap to remove the focus when Auth pages are rebuilt. This will also allow user to remove the cursor and keyboard from the screen on tapping the screen.
> Made text in TextFormField more readable 

- lib/screens/login_page.dart
- lib/screens/signup_page.dart
- lib/screens/splashscreen.dart
In response to issue #6 I have added snackbars warning if any of the FormField is empty or something is wrong with the data given.
> Added Snackbar message on Auth pages

- lib/screens/signup_page.dart
i have changed the signup_page.dart ui in the bottom of it, Now it looks more great. you can have a look at this by clicking on below link.
https://i.ibb.co/M8bs1S9/Screenshot-20221004-113210.png. 
Thank You.
> signup_page.dart ui was changed

- CONTRIBUTING.md
- README.md
#29 issue solved, please could you merge my pr with the JWOC label.
> Updated the readme , documentation

- CODE_OF_CONDUCT.md
- LICENSE.md
> Added CODE_OF_CONDUCT and LICENSE

- lib/screens/homepage.dart
- lib/screens/movie_details/actors_tile.dart
- lib/screens/movie_details/movie_details_screen.dart
- lib/shared/background_painter.dart
- lib/shared/custom_paints.dart
- pubspec.yaml
The movie details screen has been added into the nav bar item as a temp screen , remove it from the widget list and replace it with the explore page once done with the screen view. #35 issue is solved under JWOC
> Solves issue Full screen page to be coded #35 under JWOC

- lib/app/errors/errors.dart
- lib/app/errors/failure.dart
- lib/app/errors/failure_ext.dart
- lib/app/errors/type_defs.dart
- lib/app/theme/app_theme.dart
- lib/app/utils/snackbar/snackbar.dart
- lib/main.dart
- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/authentication/data/auth_api_impl.dart
- lib/src/models/user_model.dart
- lib/src/models/user_model.freezed.dart
- lib/src/models/user_model.g.dart
- lib/src/providers/firestore_provider.dart
- lib/src/providers/user_provider.dart
- pubspec.lock
- pubspec.yaml
Get and set user data in firebase database
> set and get user choices from Firestore #45 under JWOC

- lib/app/constants/api_urls.dart
- lib/app/constants/constants.dart
- lib/app/constants/enums.dart
- lib/app/errors/failure_ext.dart
- lib/src/app.dart
- lib/src/features/home/data/tmdb_api.dart
- lib/src/features/home/presentation/home_view/components/home.dart
- lib/src/features/home/presentation/home_view/home_screen.dart
- lib/src/models/all_genres_model.dart
- lib/src/models/genres_model.dart
- lib/src/models/genres_model.freezed.dart
- lib/src/models/genres_model.g.dart
- lib/src/providers/global_providers.dart
- lib/src/providers/http_base_provider.dart
- pubspec.lock
- pubspec.yaml
Load the data from server , just replace the keys with your keys in the constants file and you are good to go
> Load movies on the basis of genre like thriller  and horror as it was present in prevoius homepage from tmdb

- lib/src/app.dart
- lib/src/features/home/data/tmdb_api.dart
- lib/src/features/home/presentation/home_view/components/home.dart
- lib/src/features/home/presentation/home_view/home_screen.dart
- lib/src/features/home/presentation/movie_details/actors_tile.dart
- lib/src/features/home/presentation/movie_details/movie_details_screen.dart
- lib/src/models/cast_model.dart
- lib/src/models/cast_model.freezed.dart
- lib/src/models/cast_model.g.dart
- lib/src/models/genres_model.dart
- lib/src/models/genres_model.freezed.dart
- lib/src/models/genres_model.g.dart
- pubspec.lock
- pubspec.yaml
Hi there , moving to movie details is done, therer was one issue though , as we dont have firebase implemented yet so i dont have the user id to create the document in firebase, i have made the function to add it to the db btw but after auth is finished then only we can achieve that. Issue #46 is solved.
> TmDB API Integration (ii) #46 under JWOC

- lib/src/features/home/presentation/home_view/components/home.dart
- lib/src/features/home/presentation/movie_details/movie_details_screen.dart
- lib/src/shared/custom_hero.dart
Hero animation transition fixed , no yellow lines appear under Text widgets now during transiton
> Issue with Hero transition in homepage under JWOC #52 fixed under JWOC

- lib/app/errors/failure_ext.dart
- lib/app/utils/snackbar/show_info_snackbar.dart
- lib/app/utils/snackbar/snackbar_ext.dart
- lib/app/utils/textfield_validators.dart
- lib/src/app.dart
- lib/src/features/authentication/app/controller/signup_controller.dart
- lib/src/features/authentication/app/state/signup_state.dart
- lib/src/features/authentication/controller/auth_controller.dart
- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/authentication/data/auth_api_impl.dart
- lib/src/features/authentication/presentation/login/login_screen.dart
- lib/src/features/authentication/presentation/signup/signup_screen.dart
- lib/src/features/splash/presentation/splash_screen.dart
- lib/src/providers/firestore_provider.dart
- lib/src/providers/user_provider.dart
- lib/src/shared/loading_dialog.dart
- pubspec.lock
- pubspec.yaml
Full signup implementation using riverpod. To know more check firestore db about the sample user i created solved under JWOC #53
> Firebase auth , with email password #53 solved under JWOC

- lib/src/features/authentication/presentation/login/login_screen.dart
> correction of UI on signup and sign in page #59

- lib/src/features/authentication/app/controller/login_controller.dart
- lib/src/features/authentication/app/state/login_state.dart
- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/authentication/data/auth_api_impl.dart
- lib/src/features/authentication/presentation/login/login_screen.dart
- lib/src/features/authentication/presentation/signup/signup_screen.dart
- lib/src/routes/router.dart
Solved firebase login using riverpod
> Firebase login with email password #55 under JWOC

- lib/main.dart
- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/home/app/controller/favourites_controller.dart
- lib/src/features/home/app/controller/search_controller.dart
- lib/src/features/home/data/tmdb_api.dart
- lib/src/providers/firestore_provider.dart
- lib/src/providers/global_providers.dart
- lib/src/providers/http_base_provider.dart
- lib/src/providers/local_storage_provider.dart
- lib/src/providers/provider_observer.dart
- lib/src/providers/theme_provider.dart
- lib/src/providers/user_provider.dart
- pubspec.lock
- pubspec.yaml
Logging of providers in the provider scrope globally across the application whenever any values is updated, failed, added
> Add Provider Observer globally with proper logging #64 solved under JWOC

- lib/src/features/home/app/controller/favourites_controller.dart
- lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
- lib/src/features/home/presentation/explore_screen/explore.dart
- lib/src/features/home/presentation/favourites/favourites_screen.dart
- lib/src/features/home/presentation/home_view/components/home.dart
- lib/src/features/home/presentation/profile/profile.dart
- lib/src/providers/firestore_provider.dart
This is with respect to the issue for the currently logged in user
> Show customised message , name of currently logged in user

- lib/main.dart
- lib/src/features/home/app/controller/favourites_controller.dart
- lib/src/features/home/app/controller/search_controller.dart
- lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
- lib/src/features/home/presentation/explore_screen/explore.dart
- lib/src/features/home/presentation/favourites/favourites_screen.dart
- lib/src/shared/shimmer_loaders.dart
> Shimmer loaders 

- lib/app/constants/enums.dart
- lib/src/providers/network_checker_provider.dart
- lib/src/shared/network_checker.dart
Provide stream during connection and reacts to changes when connectivity status emits a new event. Solves issue #70
> Network Checker using riverpod under  JWOC

- lib/app/theme/app_theme.dart
- lib/main.dart
- lib/src/app.dart
- lib/src/features/authentication/presentation/signup/signup_screen.dart
- lib/src/features/home/presentation/explore_screen/explore.dart
- lib/src/features/home/presentation/favourites/favourites_screen.dart
- lib/src/features/home/presentation/home_view/components/home.dart
- lib/src/features/home/presentation/movie_details/actors_tile.dart
- lib/src/features/home/presentation/movie_details/movie_details_screen.dart
- lib/src/features/home/presentation/profile/profile.dart
- pubspec.lock
- pubspec.yaml
> google fonts added with text theming

- .gitignore
- lib/main.dart
- lib/src/features/authentication/app/controller/forgot_password_controller.dart
- lib/src/features/authentication/app/state/forgot_password_state.dart
- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/authentication/data/auth_api_impl.dart
- lib/src/features/authentication/presentation/forgot_password/forgot_password_screen.dart
- lib/src/features/authentication/presentation/login/login_screen.dart
- lib/src/routes/router.dart
forgot password screen with ability to send the reset link to the destination email address with the provided email id
> Firebase forgot password service using riverpod #78

- lib/src/features/authentication/app/controller/forgot_password_controller.dart
- lib/src/features/authentication/app/state/forgot_password_state.dart
- lib/src/features/authentication/presentation/forgot_password/forgot_password_screen.dart
- pubspec.lock
- pubspec.yaml
> Pinput field to autocatch OTP is mobile field is reset 

- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/authentication/data/auth_api_impl.dart
- lib/src/features/authentication/presentation/signup/signup_screen.dart
- lib/src/features/home/app/controller/logout_controller.dart
- lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
- lib/src/features/home/presentation/explore_screen/explore.dart
- lib/src/features/home/presentation/favourites/favourites_screen.dart
- lib/src/features/home/presentation/home_view/components/fulldetails.dart
- lib/src/features/home/presentation/home_view/components/home.dart
- lib/src/features/home/presentation/home_view/home_screen.dart
- lib/src/features/home/presentation/movie_details/actors_tile.dart
- lib/src/features/home/presentation/movie_details/movie_details_screen.dart
- lib/src/features/home/presentation/profile/components/logout_dialog.dart
- lib/src/features/home/presentation/profile/profile.dart
- lib/src/features/home/presentation/reccomendations.dart
- lib/src/features/home/presentation/trending/trending_movies_screen.dart
Clear provider data and signout firebase session
> Logout user and clear any sort of data in local storage or provider #82

- lib/src/features/authentication/app/controller/login_controller.dart
- lib/src/features/authentication/data/auth_api.dart
- lib/src/features/authentication/data/auth_api_impl.dart
- lib/src/features/authentication/presentation/login/login_screen.dart
social signin using google and firebase
> Allow Google login functionality #84

- lib/src/features/authentication/app/controller/login_controller.dart
- lib/src/features/home/data/tmdb_api.dart
- lib/src/features/home/presentation/trending/trending_movies_screen.dart
> Show movie details from the grid of trending movies using TMDB #86
